name: game001
description: "Welcome to Ngai's Call, a captivating 2D top-down game built with Flutter and the Flame engine. Embark on a spiritual journey through a vibrant forest, collecting ancient Kikuyu wisdom while evading the ominous red spirits that seek to thwart your path. Can you survive the trials and gather enough wisdom to honor the ancestors?"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/bird.png
  uses-material-design: true